### ISSUE TITLE
[.profile]: Redundancy with exporting Guix extra profiles' share directories.

### ISSUE THREAD

**Issue by ghost** [daviwil/dotfiles#13]
I would like to inform that this section (https://github.com/daviwil/dotfiles/blob/master/.profile#L43) is not needed as this section (https://github.com/daviwil/dotfiles/blob/master/.profile#L8) exports them already.

**Comment by tex** [comment]
So is it redundant or not? Does XDG separate export?

**Comment by ghost** [comment]
@tex It was a mistake. Sorry.
