### ISSUE TITLE
Evil magit conflict on update

### ISSUE THREAD

**Issue by NicolasIriarte** [daviwil/dotfiles#4]
Recently evil-magit is part of evil-collection. So the `(use-package evil-magit ...` is no longer needed (cause errors on magit-status). 

More info: [here](https://github.com/emacs-evil/evil-magit/issues/87)

**Comment by daviwil** [comment]
Yep, unfortunately I haven't been able to update my config just yet because Guix (which I use to manage my Emacs packages) hasn't updated `evil-collection` yet to a version with the `evil-magit` bindings moved over.

**Comment by NicolasIriarte** [comment]
I'll let this issue open until fixed. I'm reviewing (almost) all your configuration and I find some other littles issues. Do you prefer continuing this thread or making new ones with every one?

**Comment by daviwil** [comment]
> Do you prefer continuing this thread or making new ones with every one?

Sorry I forgot to reply to this!  Sure, definitely file issues for anything you find.

Finally got the `evil-magit` issue fixed as of https://github.com/daviwil/dotfiles/commit/5dc7f6b205962d4bfd0e6e20701b9c8c6d04e165
